[workspace]
members = ["plugin"]
default-members = ["plugin"]

[patch.crates-io]
lv2 = { git = "https://github.com/davemollen/rust-lv2.git", branch="master" }
lv2-atom = { git = "https://github.com/davemollen/rust-lv2.git", branch="master" }
lv2-sys = { git = "https://github.com/davemollen/rust-lv2.git", branch="master" }
lv2-options = { git = "https://github.com/davemollen/rust-lv2.git", branch="master" }
lv2-buf-size = { git = "https://github.com/davemollen/rust-lv2.git", branch="master" }
lv2-parameters = { git = "https://github.com/davemollen/rust-lv2.git", branch="master" }
lv2-ui = { git = "https://github.com/davemollen/rust-lv2.git", branch="master" }